// This file automatically generated by MOKO KSwift (https://github.com/icerockdev/moko-kswift)
//
import MultiPlatformLibrary

/**
 * selector: ClassContext/dev.icerock.moko:shared/dev/icerock/moko/paging/sample/declarativeui/ListUnit */
public enum ListUnitKs {

  case productUnit(ListUnitProductUnit)
  case loading

  var sealed: ListUnit {
    switch self {
    case .productUnit(let obj):
      return obj as! MultiPlatformLibrary.ListUnit
    case .loading:
      return MultiPlatformLibrary.ListUnitLoading() as! MultiPlatformLibrary.ListUnit
    }
  }

  public init(_ obj: ListUnit) {
    if let obj = obj as? MultiPlatformLibrary.ListUnitProductUnit {
      self = .productUnit(obj)
    } else if obj is MultiPlatformLibrary.ListUnitLoading {
      self = .loading
    } else {
      fatalError("ListUnitKs not syncronized with ListUnit class")
    }
  }

}
